### ISSUE TITLE
ERR_INVALID_ARG_TYPE error on npm start

### ISSUE THREAD

**Issue by eugeneindigo** [jamesgeorge007/csstox#3]
Getting below error on `npm start`. It is due to a [bug](https://github.com/facebook/create-react-app/issues/8490) which has been mentioned in create-react-app repository. The problem is resolved if you upgrade react-scripts version to 3.4.0 or higher.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at noopServiceWorkerMiddleware (/private/tmp/csstox/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/private/tmp/csstox/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/private/tmp/csstox/node_modules/express/lib/router/index.js:317:13)
    at /private/tmp/csstox/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/private/tmp/csstox/node_modules/express/lib/router/index.js:335:12)
    at next (/private/tmp/csstox/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/private/tmp/csstox/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/private/tmp/csstox/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by eugeneindigo** [comment]
I couldn't create a PR due to permission restrictions.

**Comment by jamesgeorge007** [comment]
@eugeneindigo thank you for reporting the issue ❤️

**Comment by jamesgeorge007** [comment]
> I couldn't create a PR due to permission restrictions.

Oh that's odd, may I know what shows up?

**Comment by eugeneindigo** [comment]
I am getting below message.

`ERROR: Permission to jamesgeorge007/csstox.git denied to eugeneindigo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by jamesgeorge007** [comment]
Oops, you're required to fork the repo and later open a PR.

**Comment by eugeneindigo** [comment]
I see, thank you.
